# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
 
trigger:  
  - main

pool: default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'


steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      configuration: $(buildConfiguration)

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      configuration: $(buildConfiguration)

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
      StoreAsTar: true