# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
 
trigger:  
  - main

pool: default

variables:
  buildConfiguration: 'Release'


steps:

  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: '5.5.1'
      checkLatest: true

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      configuration: $(buildConfiguration)
      projects: "**/*.csproj"

  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      packagesToPack: '**/*.csproj'


  - task: DotNetCoreCLI@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '317f01e8-1d31-48f2-9477-d1c1aca0a01d/3780be0b-e340-40f7-9d34-a900b0cf58be'
  
